### ISSUE TITLE
Paper不支持 类名获取异常

### ISSUE THREAD

**Issue by Shizuri23** [Iseason2000/DeEnchantment#1]
[07:04:06 INFO]: [负魔书] 负魔注册完毕(0/0)
[07:04:07 INFO]: [负魔书] 负魔应用于：铁砧、箱子、附魔台、怪物、村民、钓鱼、给予、
[07:04:07 ERROR]: Error occurred while enabling DeEnchantment v1.0.0 (Is it up to date?)
>java.lang.Exception: 类名获取异常!
at top.iseason.kotlin.deenchantment.utils.ClassGetter.processJarfile(ClassGetter.kt:42) ~[?:?]
at top.iseason.kotlin.deenchantment.utils.ClassGetter.<init>(ClassGetter.kt:16) ~[?:?]
at top.iseason.kotlin.deenchantment.manager.ListenerManager.registerEnchantments(ListenerManager.kt:21) ~[?:?]
at top.iseason.kotlin.deenchantment.manager.ListenerManager.registerListeners(ListenerManager.kt:16) ~[?:?]
at top.iseason.kotlin.deenchantment.manager.ConfigManager.reload(ConfigManager.kt:39) ~[?:?]
at top.iseason.kotlin.deenchantment.manager.ConfigManager.init(ConfigManager.kt:25) ~[?:?]
at top.iseason.kotlin.deenchantment.DeEnchantmentPlugin.onEnable(DeEnchantmentPlugin.kt:15) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-63]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-63]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-63]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-63]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-63]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-63]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-63]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-63]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-63]
at java.lang.Thread.run(Thread.java:831) [?:?]
[07:04:07 INFO]: [DeEnchantment] Disabling DeEnchantment v1.0.0
[07:04:07 INFO]: [负魔书] 插件已注销！

**Comment by Iseason2000** [comment]
请提供paper端的版本以便排除问题

**Comment by Iseason2000** [comment]
已修复，请下载最新的1.0.3版本
