### ISSUE TITLE
Could not pass event PrepareAnvilEvent to DeEnchantment

### ISSUE THREAD

**Issue by RanWhite** [Iseason2000/DeEnchantment#18]
**插件版本:** 
1.3.0
**服务端版本：**
1.19
### 问题描述
服务器忽然卡顿
看一下日志 发现了这个

### 报错截图
Could not pass event PrepareAnvilEvent to DeEnchantment v1.3.0
java.lang.NullPointerException: null
	at top.iseason.deenchantment.listeners.controllers.AnvilListener.onPrepareAnvilEvent(AnvilListener.kt:71) ~[DeEnchantment-1.3.0-all.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:git-Pufferfish-11]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1672) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.world.inventory.ItemCombinerMenu.slotsChanged(ItemCombinerMenu.java:81) ~[?:?]
	at net.minecraft.world.inventory.ItemCombinerMenu$1.setChanged(ItemCombinerMenu.java:25) ~[?:?]
	at net.minecraft.world.SimpleContainer.setItem(SimpleContainer.java:203) ~[?:?]
	at net.minecraft.world.inventory.Slot.set(Slot.java:59) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.world.inventory.AbstractContainerMenu.moveItemStackTo(AbstractContainerMenu.java:860) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.moveItemStackTo(AbstractContainerMenu.java:760) ~[?:?]
	at net.minecraft.world.inventory.ItemCombinerMenu.quickMoveStack(ItemCombinerMenu.java:125) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:537) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:380) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3056) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1360) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1337) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1330) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1408) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1189) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:304) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:57:54] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to DeEnchantment v1.3.0
java.lang.NullPointerException: null
	at top.iseason.deenchantment.listeners.controllers.AnvilListener.onPrepareAnvilEvent(AnvilListener.kt:71) ~[DeEnchantment-1.3.0-all.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:git-Pufferfish-11]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1672) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.world.inventory.ItemCombinerMenu.slotsChanged(ItemCombinerMenu.java:81) ~[?:?]
	at net.minecraft.world.inventory.ItemCombinerMenu$1.setChanged(ItemCombinerMenu.java:25) ~[?:?]
	at net.minecraft.world.inventory.Slot.setChanged(Slot.java:69) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.world.inventory.Slot.set(Slot.java:60) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.world.inventory.AbstractContainerMenu.moveItemStackTo(AbstractContainerMenu.java:860) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.moveItemStackTo(AbstractContainerMenu.java:760) ~[?:?]
	at net.minecraft.world.inventory.ItemCombinerMenu.quickMoveStack(ItemCombinerMenu.java:125) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:537) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:380) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3056) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1360) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1337) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1330) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1408) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1189) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:304) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:57:54] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to DeEnchantment v1.3.0
java.lang.NullPointerException: null
	at top.iseason.deenchantment.listeners.controllers.AnvilListener.onPrepareAnvilEvent(AnvilListener.kt:71) ~[DeEnchantment-1.3.0-all.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor35.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:git-Pufferfish-11]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:666) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[pufferfish-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1672) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.world.inventory.ItemCombinerMenu.slotsChanged(ItemCombinerMenu.java:81) ~[?:?]
	at net.minecraft.world.inventory.ItemCombinerMenu$1.setChanged(ItemCombinerMenu.java:25) ~[?:?]
	at net.minecraft.world.inventory.Slot.setChanged(Slot.java:69) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.world.inventory.AbstractContainerMenu.moveItemStackTo(AbstractContainerMenu.java:865) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.moveItemStackTo(AbstractContainerMenu.java:760) ~[?:?]
	at net.minecraft.world.inventory.ItemCombinerMenu.quickMoveStack(ItemCombinerMenu.java:125) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:537) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:380) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3056) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1360) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1337) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1330) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1408) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1189) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:304) ~[pufferfish-1.19.jar:git-Pufferfish-11]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Iseason2000** [comment]
如果是插件运行了一段时间突然这样的请先尝试重载插件
如果是插件放进去没多久就这样的可能是兼容性问题，我会尝试修复

**Comment by Iseason2000** [comment]
已修复铁砧报错问题 https://github.com/Iseason2000/DeEnchantment/releases/tag/1.3.1
