### ISSUE TITLE
测试中出现的bug

### ISSUE THREAD

**Issue by Cherisss** [Iseason2000/DeEnchantment#22]
**插件版本** :  2.0.1
**服务端版本**: purpur-1.18.2-1632

**bug描述**
基本上测试了一轮，问题有这些：
1，单个附魔配置文件中的conflict项不能生效，这边试了自带的永存祝福和灵魂绑定，非op下生存模式仍可以附魔。此外自己添加的原版附魔如在DE_SOUL_SPEED附魔下conflict里添加SOUL_SPEED同样不能生效。
2，2.0.1拉扯不能生效，但1.3.1的吸引可以生效，拉扯有小概率把生物拉到天上老高，生物直接飞天上然后摔死。
3，2.0.1牵引之刃不能生效，但1.3.1的牵引可以生效，暂时未发现有生物飞天的情况。
4，指令de add [附魔] [等级] 时，所有等级tab补全都为1，2，3，不影响什么但是推荐稍作优化一下。
5，负荆请罪建议修改描述，这里测的只有在疾跑跳跃时才会有概率受伤（也可能是我测的不对）
6，Minecraft游戏机制导致神速在增加箭矢速度的同时也会增加箭矢伤害，建议修改描述（直接修伤害估计不现实。。minecraft游戏机制决定的）
7，弩的反弹附魔没有效果，在1.3.1中正常
*8，严重bug！三叉戟附魔背叛以后如果被溺尸拿走，溺尸扔三叉戟攻击玩家时会同时刷出两把三叉戟，一把在地上可拾取，一把扔到玩家玩家直接拿到（应该是这样，反正会刷两把一样的三叉戟）

**报错内容**

下面的报错是在使用"拉扯"附魔时出现的
[Server thread/ERROR]: Could not pass event DeEntityProjectileEvent to DeEnchantment v2.0.1
java.lang.IllegalArgumentException: x not finite
	at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.util.Vector.checkFinite(Vector.java:814) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEntity.setVelocity(CraftEntity.java:446) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at top.iseason.bukkit.deenchantment.listeners.enchantments.Punch.onEntityDamageByEntityEvent(Punch.kt:23) ~[DeEnchantment-2.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor829.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at top.iseason.bukkit.deenchantment.command.MainCommandKt.call(MainCommand.kt:3081) ~[DeEnchantment-2.0.1.jar:?]
	at top.iseason.bukkit.deenchantment.listeners.triggers.EntityDeEnchantCaller.onPlayerAttack(EntityDeEnchantCaller.kt:24) ~[DeEnchantment-2.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor847.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:248) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1169) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1018) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:971) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1203) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2134) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1386) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:354) ~[?:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:427) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:231) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:222) ~[?:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:305) ~[?:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[?:?]
	at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1218) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:697) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:675) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1621) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

下面的报错是在使用背叛时出现的
[Server thread/ERROR]: Could not pass event ProjectileHitEvent to DeEnchantment v2.0.1
java.lang.UnsupportedOperationException: Cannot set drop chance for PlayerInventory
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryPlayer.setItemInMainHandDropChance(CraftInventoryPlayer.java:305) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at top.iseason.bukkit.deenchantment.listeners.enchantments.Loyalty.onProjectileHitEvent(Loyalty.kt:57) ~[DeEnchantment-2.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor40.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1439) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:219) ~[?:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:305) ~[?:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[?:?]
	at net.minecraft.world.entity.projectile.ThrownTrident.tick(ThrownTrident.java:90) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1218) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:697) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:675) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1621) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Iseason2000** [comment]
感谢反馈，我会尽快修复

**Comment by Iseason2000** [comment]
最新的2.0.2已修复上述问题
其中
第1点 冲突功能已修复，负魔默认与原附魔冲突，无法修改，只能冲突只对负魔有效，对其他插件的附魔无效，如有需要后续将会添加该功能 
第3点 牵引之刃是对被横扫的实体生效，对直接攻击的目标无效
第4点 tab补全完全是静态的，所以无法根据负魔最高等级进行推荐
第6点 我觉得没有必要特别指出速度会影响伤害，因为这是原版特性
