### ISSUE TITLE
无端报错

### ISSUE THREAD

**Issue by QuickLight** [Iseason2000/DeEnchantment#40]
**插件版本** :  2.0.0
**服务端版本**: purpur-1.20.1

**bug描述**

**重现步骤**
1. ...
2. ...
3. ...

**报错截图**
[10:22:05 WARN]: [DeEnchantment] Plugin DeEnchantment v2.1.9 generated an exception while executing task 21306
java.util.ConcurrentModificationException: null
        at java.util.LinkedHashMap$LinkedHashIterator.remove(LinkedHashMap.java:777) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.removeGoal(GoalSelector.java:79) ~[?:?]
        at net.minecraft.world.entity.monster.AbstractSkeleton.reassessWeaponGoal(AbstractSkeleton.java:180) ~[?:?]
        at net.minecraft.world.entity.monster.AbstractSkeleton.setItemSlot(AbstractSkeleton.java:256) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.setItemSlot(LivingEntity.java:2570) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftEntityEquipment.setEquipment(CraftEntityEquipment.java:163) ~[paper-1.20.1.jar:git-Paper-63]
        at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftEntityEquipment.setItemInMainHand(CraftEntityEquipment.java:51) ~[paper-1.20.1.jar:git-Paper-63]
        at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftEntityEquipment.setItemInMainHand(CraftEntityEquipment.java:46) ~[paper-1.20.1.jar:git-Paper-63]
        at top.iseason.bukkit.deenchantment.listeners.controllers.EntitySpawnListener.onCreatureSpawnEvent$lambda$0(EntitySpawnListener.kt:27) ~[DeEnchantment-2.1.9.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-63]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-63]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**其他信息**

**Comment by Iseason2000** [comment]
该问题发生在处理生成的怪物身上的突变装备时异步设置装备时。
如果频繁出现的话请先在config.yml中将spawn关闭，并等待修复后再开启。
预计将在今日修复
