### ISSUE TITLE
不支持1.20.3/1.20.4

### ISSUE THREAD

**Issue by CuteLittleSky** [Iseason2000/DeEnchantment#43]
**插件版本** :  2.1.11
**服务端版本**: purpur-1.20.4-2106

**报错截图**
`[14:29:07] [Server thread/INFO]: [DeEnchantment] Enabling DeEnchantment v2.1.11
[14:29:07] [Server thread/INFO]: [DeEnchantment] ██████╗ ███████╗███████╗███╗   ██╗ ██████╗██╗  ██╗ █████╗ ███╗   ██╗████████╗
[14:29:07] [Server thread/INFO]: [DeEnchantment] ██╔══██╗██╔════╝██╔════╝████╗  ██║██╔════╝██║  ██║██╔══██╗████╗  ██║╚══██╔══╝
[14:29:07] [Server thread/INFO]: [DeEnchantment] ██║  ██║█████╗  █████╗  ██╔██╗ ██║██║     ███████║███████║██╔██╗ ██║   ██║   
[14:29:07] [Server thread/INFO]: [DeEnchantment] ██║  ██║██╔══╝  ██╔══╝  ██║╚██╗██║██║     ██╔══██║██╔══██║██║╚██╗██║   ██║   
[14:29:07] [Server thread/INFO]: [DeEnchantment] ██████╔╝███████╗███████╗██║ ╚████║╚██████╗██║  ██║██║  ██║██║ ╚████║   ██║   
[14:29:07] [Server thread/INFO]: [DeEnchantment] ╚═════╝ ╚══════╝╚══════╝╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝   
[14:29:07] [Server thread/ERROR]: Error occurred while enabling DeEnchantment v2.1.11 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bukkit.enchantments.Enchantment.<init>(org.bukkit.NamespacedKey)'
	at top.iseason.bukkit.deenchantment.manager.DeEnchantmentWrapper.<init>(DeEnchantmentWrapper.kt:10) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.manager.DeEnchantments.<clinit>(DeEnchantments.kt:16) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.settings.Config.onDisable(Config.kt:95) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.settings.Config.reload(Config.kt:79) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.DeEnchantment.onEnable(DeEnchantment.kt:34) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.libs.core.BukkitTemplate.onEnable(BukkitTemplate.java:142) ~[DeEnchantment-2.1.11.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:676) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:29:07] [Server thread/INFO]: [DeEnchantment] Disabling DeEnchantment v2.1.11
[14:29:07] [Server thread/ERROR]: Error occurred while disabling DeEnchantment v2.1.11
java.lang.NoClassDefFoundError: Could not initialize class top.iseason.bukkit.deenchantment.manager.DeEnchantments
	at top.iseason.bukkit.deenchantment.settings.Config.onDisable(Config.kt:95) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.DeEnchantment.onDisable(DeEnchantment.kt:44) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.libs.core.BukkitTemplate.onDisable(BukkitTemplate.java:152) ~[DeEnchantment-2.1.11.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:194) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:676) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[purpur-1.20.4.jar:git-Purpur-2106]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'void org.bukkit.enchantments.Enchantment.<init>(org.bukkit.NamespacedKey)' [in thread "Server thread"]
	at top.iseason.bukkit.deenchantment.manager.DeEnchantmentWrapper.<init>(DeEnchantmentWrapper.kt:10) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.manager.DeEnchantments.<clinit>(DeEnchantments.kt:16) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.settings.Config.onDisable(Config.kt:95) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.settings.Config.reload(Config.kt:79) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.DeEnchantment.onEnable(DeEnchantment.kt:34) ~[DeEnchantment-2.1.11.jar:?]
	at top.iseason.bukkit.deenchantment.libs.core.BukkitTemplate.onEnable(BukkitTemplate.java:142) ~[DeEnchantment-2.1.11.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2106]
	... 10 more`

**其他信息**

**Comment by Iseason2000** [comment]
1.20.3 开始附魔注册逻辑被重写，短时间无法支持

**Comment by TheFlareStar-Re** [comment]
大概什么时候能支持呢

**Comment by Iseason2000** [comment]
很抱歉，经过一定时间的研究，暂未找到有效的支持 1.20.3/4 的方法。
本人精力有限且技术不足，故而本项目将进行归档。
感谢您的使用
